terminos = {
    "Array": "Estructura de datos que contiene múltiples elementos, accesibles por un índice.",
    "Algorithm": "Conjunto de pasos ordenados para resolver un problema o realizar una tarea.",
    "API": "Reglas y definiciones que permiten que aplicaciones se comuniquen entre sí.",
    "Boolean": "Tipo de dato que puede ser verdadero o falso.",
    "Break": "Instrucción que detiene un ciclo inmediatamente.",
    "Class": "Plantilla utilizada en programación orientada a objetos para crear objetos.",
    "Compiler": "Programa que traduce código fuente a un lenguaje que la máquina puede entender.",
    "Condition": "Expresión que se evalúa como verdadera o falsa.",
    "Data Structure": "Formato especializado para organizar y almacenar datos.",
    "Debug": "Proceso de encontrar y corregir errores en un programa.",
    "Dictionary": "Estructura de datos que almacena pares clave-valor.",
    "Exception": "Evento que interrumpe el flujo normal de un programa.",
    "For Loop": "Estructura que repite un bloque de código un número determinado de veces.",
    "Function": "Bloque de código reutilizable que realiza una tarea específica.",
    "Garbage Collection": "Proceso que libera memoria ocupada por objetos no utilizados.",
    "Hash": "Función que convierte datos en una cadena de longitud fija.",
    "HTTP": "Protocolo utilizado para la transmisión de datos en la web.",
    "If Statement": "Estructura que ejecuta código solo si una condición es verdadera.",
    "Inheritance": "Permite que una clase derive de otra.",
    "JSON": "Formato ligero para intercambiar datos.",
    "Key": "Parte de un par clave-valor en estructuras como diccionarios.",
    "Loop": "Estructura que repite un bloque de código mientras se cumpla una condición.",
    "Library": "Colección de funciones y recursos reutilizables.",
    "Method": "Función que pertenece a un objeto o clase.",
    "Module": "Archivo que contiene código reutilizable.",
    "Null": "Valor que indica la ausencia de un valor.",
    "Object": "Instancia de una clase que agrupa datos y métodos.",
    "Operator": "Símbolo que realiza operaciones en uno o más operandos.",
    "Parameter": "Valores que se pasan a una función.",
    "Pointer": "Variable que almacena la dirección de memoria de otro dato.",
    "Queue": "Estructura de datos que sigue el principio FIFO (primero en entrar, primero en salir).",
    "Recursion": "Técnica donde una función se llama a sí misma.",
    "Return": "Palabra clave que termina la ejecución de una función y devuelve un valor.",
    "String": "Tipo de dato que representa una secuencia de caracteres.",
    "Syntax": "Reglas que definen la estructura válida de un programa.",
    "Thread": "Unidad de ejecución dentro de un proceso que puede ejecutarse concurrentemente.",
    "Tuple": "Tipo de dato que agrupa varios valores, pero es inmutable.",
    "Unary Operator": "Operador que actúa sobre un solo operando.",
    "URL": "Dirección que identifica un recurso en la web.",
    "Variable": "Espacio en memoria que almacena datos que pueden cambiar durante la ejecución.",
    "While Loop": "Repite un bloque de código mientras una condición sea verdadera.",
    "WebSocket": "Protocolo que permite la comunicación bidireccional en tiempo real entre cliente y servidor.",
    "XML": "Lenguaje utilizado para el intercambio de datos.",
    "YAML": "Lenguaje de serialización de datos legible por humanos.",
    "Zero-Based Indexing": "Sistema donde el primer elemento de una lista tiene un índice de 0."
}

# crear un diccionario de listas para agrupar terminos por letra inicial
terminos_por_letra = {}

